### PR TITLE
Refer to gitignoresource in case of ./. anti pattern

### PR DESCRIPTION
**Pull request by jappeace**
Knowing about that significantly increased the ergonimics
of nix-shell for me. So I think it's good to mention it.

### CODE REVIEW

**Comment by domenkozar** [comment]
recheckcla

**Comment by jappeace** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jappeace** [comment]
recheckcla

**Comment by domenkozar** [comment]
thanks!

**Pull request merged**
