### PR TITLE
building-and-running-docker-images: Set system

### PR DESCRIPTION
**Pull request by roberth**
This will help macOS users. While alternatives are possible[1]
this is the simplest solution.

1: https://github.com/NixOS/nixpkgs/pull/115083

### CODE REVIEW

**Comment by mpscholten** [comment]
I tried to build a hello world docker image by following the instructions. It seems that the system requirements here make it impossible to build on mac. I always get this:

```
marc@Marcs-MacBook-Pro-2 ihp-forum % nix-build docker.nix
these derivations will be built:
  /nix/store/jpbk75cf7qq15xqc1v4w4nacbpqp34vz-hello-docker-config.json.drv
  /nix/store/0vxrlcy2v0h824f50kjwsw1qhzlwjqah-docker-layer-hello-docker.drv
  /nix/store/767rkinbjvhjfk646ph5029w3dd9n1a1-runtime-deps.drv
  /nix/store/8psqf5z2k3rfkv3dyk90f59h3mvb6gfb-docker-image-hello-docker.tar.gz.drv
these paths will be fetched (90.94 MiB download, 375.84 MiB unpacked):
  /nix/store/j897lrc8dv6qci6px4qrgys0yrphsdcp-go-1.15.11
  /nix/store/vqmcbfc88q71sa7nk4ir14p49qlq7vnl-moreutils-0.65
  /nix/store/x68qga5nr2h9i5xmdks06al223qg5rh5-tarsum
error: a 'x86_64-linux' with features {} is required to build '/nix/store/jpbk75cf7qq15xqc1v4w4nacbpqp34vz-hello-docker-config.json.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}
```

Am I doing something wrong?

**Comment by mpscholten** [comment]
Got it to work with this:

```nix
{ localPkgs ? import <nixpkgs> {}
, imagePkgs ? import <nixpkgs> { system = "x86_64-linux"; }
}:

localPkgs.dockerTools.buildImage {
  name = "hello-docker";
  config = {
    Cmd = [ "${imagePkgs.hello}/bin/hello" ];
  };
}
```

**Comment by roberth** [comment]
You'll want to set up a remote builder (could be a VM) if you want to build non-trivial images that have store paths which aren't on cache.nixos.org.

**Comment by mpscholten** [comment]
Thanks :) I followed the instructions here https://github.com/LnL7/nix-docker#running-as-a-remote-builder and it's working :)

**Pull request merged**
