### PR TITLE
Set maxdepth 2 to make homepage cleaner

### PR DESCRIPTION
**Pull request by mkenigs**
I personally found it hard to skim through details about a tutorial when
I just wanted to know what each one was about

Hope this isn't too opinionated, but thought I might as well make the suggestion

### CODE REVIEW

**Comment by mkenigs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mkenigs** [comment]
recheckcla

**Comment by mkenigs** [comment]
recheckcla

**Comment by domenkozar** [comment]
Thanks!

**Pull request merged**
