### PR TITLE
reproducibile shell edits

### PR DESCRIPTION
**Pull request by sixhobbits**
small edits

### CODE REVIEW

**Comment by sixhobbits** [comment]
@domenkozar these are some smaller edits/touch ups. My larger questions after reading this one which I think would be good to address are 

* Why might it be useful to run the bash hook every time I run the shell (I imagine it can be used as part of git workflows etc, but mentioning a 'real world' example to supplement the 'hello' demonstration would help clarify this I think
* Why is the ``direnv`` command useful - I imagine developers would not need to modify their project shell.nix file that often and would probably restart the shell at least daily when they begin working on a project anyway? Or is that not a common workflow and therefore it's worth installing ``direnv`` globally on all dev machines to avoid having to restart the shell?

**Comment by sixhobbits** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sixhobbits** [comment]
recheckcla

**Comment by domenkozar** [comment]
>    Why might it be useful to run the bash hook every time I run the shell (I imagine it can be used as part of git workflows etc, but mentioning a 'real world' example to supplement the 'hello' demonstration would help clarify this I think

That's a good point! I'll add an example.

>   Why is the direnv command useful - I imagine developers would not need to modify their project shell.nix file that often and would probably restart the shell at least daily when they begin working on a project anyway? Or is that not a common workflow and therefore it's worth installing direnv globally on all dev machines to avoid having to restart the shell?

It's more that you often switch between projects during development and you want the project to just work.

It depends a bit on the worfklow, if you have one project and a terminal open all the time, then it's not that useful :)

**Comment by domenkozar** [comment]
Merging these changes since they look good! Thanks :)

**Comment by domenkozar** [comment]
Opened https://github.com/nix-dot-dev/nix.dev/issues/80 for your feedback :)

**Pull request merged**
